// Comprehensive list of international dialing codes (ISO 3166-1 alpha-2 + country name)
// Source aggregated from ITU/ISO references. Keep sorted by country name for usability.
export type CountryCode = { code: string; iso2: string; country: string };

export const COUNTRY_CODES: CountryCode[] = [
  { code: "+93", iso2: "AF", country: "Afghanistan" },
  { code: "+355", iso2: "AL", country: "Albania" },
  { code: "+213", iso2: "DZ", country: "Algeria" },
  { code: "+376", iso2: "AD", country: "Andorra" },
  { code: "+244", iso2: "AO", country: "Angola" },
  { code: "+1", iso2: "AI", country: "Anguilla" },
  { code: "+1", iso2: "AG", country: "Antigua and Barbuda" },
  { code: "+54", iso2: "AR", country: "Argentina" },
  { code: "+374", iso2: "AM", country: "Armenia" },
  { code: "+297", iso2: "AW", country: "Aruba" },
  { code: "+61", iso2: "AU", country: "Australia" },
  { code: "+43", iso2: "AT", country: "Austria" },
  { code: "+994", iso2: "AZ", country: "Azerbaijan" },
  { code: "+1", iso2: "BS", country: "Bahamas" },
  { code: "+973", iso2: "BH", country: "Bahrain" },
  { code: "+880", iso2: "BD", country: "Bangladesh" },
  { code: "+1", iso2: "BB", country: "Barbados" },
  { code: "+375", iso2: "BY", country: "Belarus" },
  { code: "+32", iso2: "BE", country: "Belgium" },
  { code: "+501", iso2: "BZ", country: "Belize" },
  { code: "+229", iso2: "BJ", country: "Benin" },
  { code: "+1", iso2: "BM", country: "Bermuda" },
  { code: "+975", iso2: "BT", country: "Bhutan" },
  { code: "+591", iso2: "BO", country: "Bolivia" },
  { code: "+387", iso2: "BA", country: "Bosnia and Herzegovina" },
  { code: "+267", iso2: "BW", country: "Botswana" },
  { code: "+55", iso2: "BR", country: "Brazil" },
  { code: "+246", iso2: "IO", country: "British Indian Ocean Territory" },
  { code: "+1", iso2: "VG", country: "British Virgin Islands" },
  { code: "+673", iso2: "BN", country: "Brunei" },
  { code: "+359", iso2: "BG", country: "Bulgaria" },
  { code: "+226", iso2: "BF", country: "Burkina Faso" },
  { code: "+257", iso2: "BI", country: "Burundi" },
  { code: "+855", iso2: "KH", country: "Cambodia" },
  { code: "+237", iso2: "CM", country: "Cameroon" },
  { code: "+1", iso2: "CA", country: "Canada" },
  { code: "+238", iso2: "CV", country: "Cape Verde" },
  { code: "+1", iso2: "KY", country: "Cayman Islands" },
  { code: "+236", iso2: "CF", country: "Central African Republic" },
  { code: "+235", iso2: "TD", country: "Chad" },
  { code: "+56", iso2: "CL", country: "Chile" },
  { code: "+86", iso2: "CN", country: "China" },
  { code: "+57", iso2: "CO", country: "Colombia" },
  { code: "+269", iso2: "KM", country: "Comoros" },
  { code: "+682", iso2: "CK", country: "Cook Islands" },
  { code: "+506", iso2: "CR", country: "Costa Rica" },
  { code: "+385", iso2: "HR", country: "Croatia" },
  { code: "+53", iso2: "CU", country: "Cuba" },
  { code: "+357", iso2: "CY", country: "Cyprus" },
  { code: "+420", iso2: "CZ", country: "Czechia" },
  { code: "+243", iso2: "CD", country: "DR Congo" },
  { code: "+45", iso2: "DK", country: "Denmark" },
  { code: "+253", iso2: "DJ", country: "Djibouti" },
  { code: "+1", iso2: "DM", country: "Dominica" },
  { code: "+1", iso2: "DO", country: "Dominican Republic" },
  { code: "+593", iso2: "EC", country: "Ecuador" },
  { code: "+20", iso2: "EG", country: "Egypt" },
  { code: "+503", iso2: "SV", country: "El Salvador" },
  { code: "+240", iso2: "GQ", country: "Equatorial Guinea" },
  { code: "+291", iso2: "ER", country: "Eritrea" },
  { code: "+372", iso2: "EE", country: "Estonia" },
  { code: "+268", iso2: "SZ", country: "Eswatini" },
  { code: "+251", iso2: "ET", country: "Ethiopia" },
  { code: "+500", iso2: "FK", country: "Falkland Islands" },
  { code: "+298", iso2: "FO", country: "Faroe Islands" },
  { code: "+679", iso2: "FJ", country: "Fiji" },
  { code: "+358", iso2: "FI", country: "Finland" },
  { code: "+33", iso2: "FR", country: "France" },
  { code: "+594", iso2: "GF", country: "French Guiana" },
  { code: "+689", iso2: "PF", country: "French Polynesia" },
  { code: "+241", iso2: "GA", country: "Gabon" },
  { code: "+220", iso2: "GM", country: "Gambia" },
  { code: "+995", iso2: "GE", country: "Georgia" },
  { code: "+49", iso2: "DE", country: "Germany" },
  { code: "+233", iso2: "GH", country: "Ghana" },
  { code: "+350", iso2: "GI", country: "Gibraltar" },
  { code: "+30", iso2: "GR", country: "Greece" },
  { code: "+299", iso2: "GL", country: "Greenland" },
  { code: "+1", iso2: "GD", country: "Grenada" },
  { code: "+590", iso2: "GP", country: "Guadeloupe" },
  { code: "+1", iso2: "GU", country: "Guam" },
  { code: "+502", iso2: "GT", country: "Guatemala" },
  { code: "+224", iso2: "GN", country: "Guinea" },
  { code: "+245", iso2: "GW", country: "Guinea-Bissau" },
  { code: "+592", iso2: "GY", country: "Guyana" },
  { code: "+509", iso2: "HT", country: "Haiti" },
  { code: "+504", iso2: "HN", country: "Honduras" },
  { code: "+36", iso2: "HU", country: "Hungary" },
  { code: "+354", iso2: "IS", country: "Iceland" },
  { code: "+91", iso2: "IN", country: "India" },
  { code: "+62", iso2: "ID", country: "Indonesia" },
  { code: "+98", iso2: "IR", country: "Iran" },
  { code: "+964", iso2: "IQ", country: "Iraq" },
  { code: "+353", iso2: "IE", country: "Ireland" },
  { code: "+972", iso2: "IL", country: "Israel" },
  { code: "+39", iso2: "IT", country: "Italy" },
  { code: "+1", iso2: "JM", country: "Jamaica" },
  { code: "+81", iso2: "JP", country: "Japan" },
  { code: "+962", iso2: "JO", country: "Jordan" },
  { code: "+7", iso2: "KZ", country: "Kazakhstan" },
  { code: "+254", iso2: "KE", country: "Kenya" },
  { code: "+686", iso2: "KI", country: "Kiribati" },
  { code: "+383", iso2: "XK", country: "Kosovo" },
  { code: "+965", iso2: "KW", country: "Kuwait" },
  { code: "+996", iso2: "KG", country: "Kyrgyzstan" },
  { code: "+856", iso2: "LA", country: "Laos" },
  { code: "+371", iso2: "LV", country: "Latvia" },
  { code: "+961", iso2: "LB", country: "Lebanon" },
  { code: "+266", iso2: "LS", country: "Lesotho" },
  { code: "+231", iso2: "LR", country: "Liberia" },
  { code: "+218", iso2: "LY", country: "Libya" },
  { code: "+423", iso2: "LI", country: "Liechtenstein" },
  { code: "+370", iso2: "LT", country: "Lithuania" },
  { code: "+352", iso2: "LU", country: "Luxembourg" },
  { code: "+261", iso2: "MG", country: "Madagascar" },
  { code: "+265", iso2: "MW", country: "Malawi" },
  { code: "+60", iso2: "MY", country: "Malaysia" },
  { code: "+960", iso2: "MV", country: "Maldives" },
  { code: "+223", iso2: "ML", country: "Mali" },
  { code: "+356", iso2: "MT", country: "Malta" },
  { code: "+692", iso2: "MH", country: "Marshall Islands" },
  { code: "+596", iso2: "MQ", country: "Martinique" },
  { code: "+222", iso2: "MR", country: "Mauritania" },
  { code: "+230", iso2: "MU", country: "Mauritius" },
  { code: "+262", iso2: "YT", country: "Mayotte" },
  { code: "+52", iso2: "MX", country: "Mexico" },
  { code: "+691", iso2: "FM", country: "Micronesia" },
  { code: "+373", iso2: "MD", country: "Moldova" },
  { code: "+377", iso2: "MC", country: "Monaco" },
  { code: "+976", iso2: "MN", country: "Mongolia" },
  { code: "+382", iso2: "ME", country: "Montenegro" },
  { code: "+1", iso2: "MS", country: "Montserrat" },
  { code: "+212", iso2: "MA", country: "Morocco" },
  { code: "+258", iso2: "MZ", country: "Mozambique" },
  { code: "+95", iso2: "MM", country: "Myanmar" },
  { code: "+264", iso2: "NA", country: "Namibia" },
  { code: "+674", iso2: "NR", country: "Nauru" },
  { code: "+977", iso2: "NP", country: "Nepal" },
  { code: "+31", iso2: "NL", country: "Netherlands" },
  { code: "+687", iso2: "NC", country: "New Caledonia" },
  { code: "+64", iso2: "NZ", country: "New Zealand" },
  { code: "+505", iso2: "NI", country: "Nicaragua" },
  { code: "+227", iso2: "NE", country: "Niger" },
  { code: "+234", iso2: "NG", country: "Nigeria" },
  { code: "+683", iso2: "NU", country: "Niue" },
  { code: "+850", iso2: "KP", country: "North Korea" },
  { code: "+389", iso2: "MK", country: "North Macedonia" },
  { code: "+47", iso2: "NO", country: "Norway" },
  { code: "+968", iso2: "OM", country: "Oman" },
  { code: "+92", iso2: "PK", country: "Pakistan" },
  { code: "+680", iso2: "PW", country: "Palau" },
  { code: "+970", iso2: "PS", country: "Palestine" },
  { code: "+507", iso2: "PA", country: "Panama" },
  { code: "+675", iso2: "PG", country: "Papua New Guinea" },
  { code: "+595", iso2: "PY", country: "Paraguay" },
  { code: "+51", iso2: "PE", country: "Peru" },
  { code: "+63", iso2: "PH", country: "Philippines" },
  { code: "+48", iso2: "PL", country: "Poland" },
  { code: "+351", iso2: "PT", country: "Portugal" },
  { code: "+1", iso2: "PR", country: "Puerto Rico" },
  { code: "+974", iso2: "QA", country: "Qatar" },
  { code: "+262", iso2: "RE", country: "Reunion" },
  { code: "+40", iso2: "RO", country: "Romania" },
  { code: "+7", iso2: "RU", country: "Russia" },
  { code: "+250", iso2: "RW", country: "Rwanda" },
  { code: "+590", iso2: "BL", country: "Saint Barthélemy" },
  { code: "+290", iso2: "SH", country: "Saint Helena" },
  { code: "+1", iso2: "KN", country: "Saint Kitts and Nevis" },
  { code: "+1", iso2: "LC", country: "Saint Lucia" },
  { code: "+590", iso2: "MF", country: "Saint Martin" },
  { code: "+508", iso2: "PM", country: "Saint Pierre and Miquelon" },
  { code: "+1", iso2: "VC", country: "Saint Vincent and the Grenadines" },
  { code: "+685", iso2: "WS", country: "Samoa" },
  { code: "+378", iso2: "SM", country: "San Marino" },
  { code: "+239", iso2: "ST", country: "Sao Tome and Principe" },
  { code: "+966", iso2: "SA", country: "Saudi Arabia" },
  { code: "+221", iso2: "SN", country: "Senegal" },
  { code: "+381", iso2: "RS", country: "Serbia" },
  { code: "+248", iso2: "SC", country: "Seychelles" },
  { code: "+232", iso2: "SL", country: "Sierra Leone" },
  { code: "+65", iso2: "SG", country: "Singapore" },
  { code: "+421", iso2: "SK", country: "Slovakia" },
  { code: "+386", iso2: "SI", country: "Slovenia" },
  { code: "+677", iso2: "SB", country: "Solomon Islands" },
  { code: "+252", iso2: "SO", country: "Somalia" },
  { code: "+27", iso2: "ZA", country: "South Africa" },
  { code: "+82", iso2: "KR", country: "South Korea" },
  { code: "+211", iso2: "SS", country: "South Sudan" },
  { code: "+34", iso2: "ES", country: "Spain" },
  { code: "+94", iso2: "LK", country: "Sri Lanka" },
  { code: "+249", iso2: "SD", country: "Sudan" },
  { code: "+597", iso2: "SR", country: "Suriname" },
  { code: "+46", iso2: "SE", country: "Sweden" },
  { code: "+41", iso2: "CH", country: "Switzerland" },
  { code: "+963", iso2: "SY", country: "Syria" },
  { code: "+886", iso2: "TW", country: "Taiwan" },
  { code: "+992", iso2: "TJ", country: "Tajikistan" },
  { code: "+255", iso2: "TZ", country: "Tanzania" },
  { code: "+66", iso2: "TH", country: "Thailand" },
  { code: "+228", iso2: "TG", country: "Togo" },
  { code: "+690", iso2: "TK", country: "Tokelau" },
  { code: "+676", iso2: "TO", country: "Tonga" },
  { code: "+1", iso2: "TT", country: "Trinidad and Tobago" },
  { code: "+216", iso2: "TN", country: "Tunisia" },
  { code: "+90", iso2: "TR", country: "Turkey" },
  { code: "+993", iso2: "TM", country: "Turkmenistan" },
  { code: "+1", iso2: "TC", country: "Turks and Caicos Islands" },
  { code: "+688", iso2: "TV", country: "Tuvalu" },
  { code: "+256", iso2: "UG", country: "Uganda" },
  { code: "+380", iso2: "UA", country: "Ukraine" },
  { code: "+971", iso2: "AE", country: "United Arab Emirates" },
  { code: "+44", iso2: "GB", country: "United Kingdom" },
  { code: "+1", iso2: "US", country: "United States" },
  { code: "+598", iso2: "UY", country: "Uruguay" },
  { code: "+998", iso2: "UZ", country: "Uzbekistan" },
  { code: "+678", iso2: "VU", country: "Vanuatu" },
  { code: "+58", iso2: "VE", country: "Venezuela" },
  { code: "+84", iso2: "VN", country: "Vietnam" },
  { code: "+681", iso2: "WF", country: "Wallis and Futuna" },
  { code: "+967", iso2: "YE", country: "Yemen" },
  { code: "+260", iso2: "ZM", country: "Zambia" },
  { code: "+263", iso2: "ZW", country: "Zimbabwe" },
];
